stages:
  - build
  - deploy

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build . -t lfg_backend:latest

deploy:
  stage: deploy
  before_script:
     - cd /apps/lfg && docker-compose exec -T api /bin/sh -c "mix ecto.migrate"
  script:
    - cd /apps/lfg && docker-compose up -d


