version: "2"
services:
  db:
    image: postgis/postgis
    restart: always
    ports:
      - "5532:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: problem_service_dev
    volumes:
      - ./data:/var/lib/postgresql/data
  test_db:
    image: postgis/postgis
    restart: always
    ports:
      - "5533:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: problem_service_test
  graphiql:
    image: plutoz/graphiql
    ports:
      - 9876:4000
