import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :event_service, EventServiceWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :ueberauth, Ueberauth.Strategy.Facebook.OAuth,
client_id: "773947543964189",
client_secret: "afaac670206d02cbc2ddfaaec0f8fb8b"

config :ueberauth, Ueberauth,
providers: [
  facebook:
    {Ueberauth.Strategy.Facebook,
     [
       default_scope: "email,public_profile,user_friends",
       callback_url: "https://group.chrisjowen.net/auth/facebook/callback"
     ]}
]


# Do not print debug messages in production
config :logger, level: :debug
